version: "3.9"

services:
  site:
    image: flutter-site-user-base
    build:
      context: .
      target: user-base
      args:
        - HOST_KERNEL_NAME
        - HOST_GROUP_ID
        - HOST_GROUP_NAME
        - HOST_USER_ID
        - HOST_USER_HOME
        - HOST_USER_NAME
    user: $HOST_USER_ID:$HOST_GROUP_ID
    command: make site-serve
    env_file:
      - shared.env
      - .env
    environment:
      - NODE_ENV=development
      - JEKYLL_ENV=development
    ports:
      - "4002:4002"
      - "35729:35729"
    volumes:
      - ./:/app
      - ./bundle:/usr/local/bundle
      - ./.pub-cache:$HOST_USER_HOME/.pub-cache
