name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

env:
  NODE_ENV: production
  NODE_VERSION: 15

jobs:

  test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # - name: "Dev channel"
          #   channel: dev
          #   experimental: true
          # - name: "Beta channel"
          #   channel: beta
          #   experimental: true
          - name: "Stable channel"
            channel: stable
            experimental: false
    steps:
      - uses: actions/checkout@v2
      - name: Install docker # Taken from https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
        run: |
          mkdir -p ~/.docker/machine/cache
          curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
          brew install docker docker-machine
          docker-machine create --driver virtualbox default
          docker-machine env default
          eval "$(docker-machine env default)"
      - name: Test
        run: make test
        env:
          TEST_TARGET_CHANNEL: ${{ matrix.channel }}
        continue-on-error: ${{ matrix.experimental }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push'
      && github.ref == 'refs/heads/main'
      && github.repository == 'flutter/website'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install firebase tools
        run: npm install -g firebase-tools
      - name: Build
        run: make build
        env:
          DISABLE_TESTS: 1
      - name: Deploy
        run: make deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_ALIAS: default
